### PR TITLE
Check for common twitter config errors before releasing

### PR DESCRIPTION
**Pull request by rsrchboy**
Here we add the BeforeRelease role, so that we can validate parts of our configuration, rather than allowing that to possibly Messify(tm) the after release process by dying because we don't have the proper twitter authentication information.

Originally I wrote this with multiple checks in mind.  However, it turned out to really be one check, to ensure we have twitter credentials available.

### CODE REVIEW

**Comment by doherty** [comment]
We don't use netrc any longer - are you sure you are patching against a current version of the code? You probably want to fork from [my repo](https://github.com/doherty/Dist-Zilla-Plugin-Twitter). I should make that clearer in a future release, as the metadata still points to this repo.

**Comment by rsrchboy** [comment]
ah-ha -- no, I'm definitely not.  The metadata for this dist shows @dagolden's repo being primary, but checking the network view it looks like your fork actually is primary.

Can that be fixed?  If it mislead me, there's a decent chance it will do the same for at least one other person :)

**Comment by doherty** [comment]
I'm not sure if it can be changed on github, but the module metadata should point to my repo instead of here once I make a new release.

**Comment by dagolden** [comment]
@doherty, It looks like github now has a "transfer ownership" option.  So if you rename your repo, I could transfer this one to you.  You'd get the issues (all 2 of them) but it means your repo wouldn't say "forked from", I think.

But you should fix the metadata on the dist, too.

**Comment by doherty** [comment]
I've fixed the metadata now.

Thanks, David. Do you know if there's a way to merge issues for the 2 repos?

**Comment by dagolden** [comment]
I don't, sorry.  You could ask Github support, I suppose.

Or, maybe there's some perl scripting possible to migrate them.  :-)

**Pull request closed without merging**
